name: Check Events Status

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check event status
        run: |
          curl -X GET https://project-sigma-beige.vercel.app/ \
          -H "Accept: application/json" \
          -H "User-Agent: GitHub-Action"